// Constantes pour les options des formulaires de scraping
// Ces constantes sont référencées dans la configuration des scrapers

export const JOB_TITLES = [
  "Director",
  "Manager",
  "Founder",
  "General Manager",
  "Consultant",
  "Chief Executive Officer",
  "Co-Founder",
  "Account Manager",
  "Chief Financial Officer",
  "Human Resources Manager",
  "Director Of Marketing",
  "Executive Director",
  "Executive Assistant",
  "Administrative Assistant",
  "Director Of Human Resources",
  "Associate",
  "Chief Operating Officer",
  "HR Manager",
  "Account Executive",
  "Business Development Manager",
  "Director Of Operations",
  "Controller",
  "Chief Technology Officer",
  "Chief Information Officer",
  "Founder & CEO",
  "Attorney",
  "IT Manager",
  "Assistant Manager",
  "Engineer",
  "Business Analyst",
  "Accountant",
  "Chief Marketing Officer",
  "Creative Director",
  "Director Of Sales",
  "Graphic Designer",
  "Analyst",
  "Human Resources Director",
  "Founder And CEO",
  "Director, Information Technology",
  "Digital Marketing Manager",
  "Business Owner",
  "Assistant Professor",
  "Branch Manager",
  "HR Director",
  "Administrator",
  "Customer Service Representative",
  "HR Business Partner",
  "Co Founder",
  "Designer",
  "Intern",
  "Lecturer",
  "Architect",
  "Director Of Information Technology",
  "Information Technology Manager",
  "Co-Founder & CEO",
  "Co-Owner",
  "Director, Human Resources",
  "Business Development",
  "IT Director",
  "Associate Professor",
  "Finance Manager",
  "Director Of Business Development",
  "Developer",
  "Business Manager",
  "Director Of Engineering",
  "Human Resources",
  "Manager, Information Technology",
  "Customer Service",
  "Key Account Manager",
  "Executive Vice President",
  "Financial Analyst",
  "HR Generalist",
  "Financial Advisor",
  "Instructor",
  "Engineering Manager",
  "Art Director",
  "Director Of Sales And Marketing",
  "Area Manager",
  "CEO & Founder",
  "Director Of Finance",
  "Data Analyst",
  "Associate Director",
  "Accounting Manager",
  "Customer Service Manager",
  "IT Specialist",
  "Account Director",
  "Data Scientist",
  "District Manager",
  "Human Resources Business Partner",
  "Co-Founder And CEO",
  "Assistant Principal",
  "Information Technology Director",
  "Facilities Manager",
  "Director Human Resources",
  "Area Sales Manager",
  "Executive",
  "Human Resources Generalist",
  "CEO & Co-Founder",
  "IT Project Manager",
  "Finance Director",
  "Head Of Marketing",
  "Independent Consultant",
  "Brand Manager",
  "Financial Controller",
  "Broker",
  "Human Resource Manager",
  "Founder, CEO",
  "Customer Success Manager",
  "CEO And Founder",
  "Director Of IT",
  "Founder/CEO",
  "IT Consultant",
  "HR Coordinator",
  "Lawyer",
  "Chief Human Resources Officer",
  "Director Of Technology",
  "Chief Operations Officer",
  "Business Development Executive",
  "HR Specialist",
  "Devops",
  "Community Manager",
  "CEO And Co-Founder",
  "Director Of Product Management",
  "Business Consultant",
  "Digital Marketing Specialist",
  "Human Resources Coordinator",
  "IT Analyst",
  "Event Manager",
  "Director Of Development",
  "Co-Founder & CTO",
  "Database Administrator",
  "HR Assistant",
  "HR Executive",
  "Business Development Representative",
  "Director Of Sales & Marketing",
  "Commercial Manager",
  "HR Consultant",
  "Lead Engineer",
  "Director Of Marketing And Communications",
  "Manager, Human Resources",
  "Assistant Project Manager",
  "Logistics Manager",
  "Assistant General Manager",
  "Lead Software Engineer",
  "Director Of Recruiting",
  "CEO/Founder",
  "Associate Creative Director",
  "Director Of Product Marketing",
  "Corporate Controller",
  "Director Of Talent Acquisition",
  "Commercial Director",
  "Chief People Officer",
  "Inside Sales Representative",
  "Devops Engineer",
  "Co-Founder And CTO",
  "Director Of Training",
  "Financial Manager",
  "Director Of Marketing Communications",
  "Finance Officer",
  "Financial Planner",
  "Accounts Manager",
  "Customer Service Associate",
  "Director HR",
];

export const SENIORITY_LEVELS = [
  "Entry",
  "Senior",
  "Manager",
  "Director",
  "VP",
  "C-Suite",
  "Owner",
  "Head",
  "Founder",
  "Partner",
];

export const DEPARTMENTS = [
  "Sales",
  "Marketing",
  "Engineering",
  "Product Management",
  "Human Resources",
  "Finance",
  "Operations",
  "Business Development",
  "Customer Success",
  "Support",
];

export const COUNTRIES = [
  "United States",
  "United Kingdom",
  "India",
  "France",
  "Canada",
  "Netherlands",
  "Brazil",
  "Australia",
  "Germany",
  "Spain",
  "Italy",
  "Switzerland",
  "Sweden",
  "South Africa",
  "Denmark",
  "Belgium",
  "Mexico",
  "Turkey",
  "United Arab Emirates",
];

export const COMPANY_SIZES = [
  "1-10",
  "11-20",
  "21-50",
  "51-100",
  "101-200",
  "201-500",
  "501-1000",
  "1001-5000",
  "5001-10000",
  "10001+",
];

export const INDUSTRIES = [
  "Banking",
  "Business Supplies & Equipment",
  "Commercial Real Estate",
  "E-Learning",
  "Education Management",
  "Events Services",
  "Financial Services",
  "Human Resources",
  "Information Technology & Services",
  "Marketing & Advertising",
  "Computer Software",
  "Internet",
  "Management Consulting",
  "Real Estate",
  "Telecommunications",
  "Hospital & Health Care",
  "Retail",
  "Construction",
  "Automotive",
  "Food & Beverages",
];

// Helper pour obtenir les options depuis une source
export function getOptionsFromSource(source: string): string[] {
  switch (source) {
    case "JOB_TITLES":
      return JOB_TITLES;
    case "SENIORITY_LEVELS":
      return SENIORITY_LEVELS;
    case "DEPARTMENTS":
      return DEPARTMENTS;
    case "COUNTRIES":
      return COUNTRIES;
    case "COMPANY_SIZES":
      return COMPANY_SIZES;
    case "INDUSTRIES":
      return INDUSTRIES;
    default:
      return [];
  }
}
